const biography = [
  'Synliga – “The blindest band in the land!”',
  'Synliga was formed in August of 1983 and the idea was to start a band that could play good original music that would have lyrics from a blind or visually impaired person’s viewpoint. The band’s main songwriter was and still is the base player Ulf Nordquist, and he wrote songs on this subject. The best of these early works are still played by the band to this day.',
  'The name Synliga means visible or a sight gang.',
  'The band continued in the same fashion for a few years, but with a few personnel changes, and had some success – the most notable being a couple of gigs on national radio.',
  'In 1988 the band was joined by drummer and singer Sven Westin and Synliga would have the same personnel for the next 9 years with Sven, Ulf and Ulf’s older brother Kaj on guitar and Ulf’s girlfriend Marie Häglerud on vocals and keyboards.',
  'In 1989 the group played outside Sweden for the first time when they participated in a music and arts festival in Havana, Cuba. The members of Synliga fell in love with the people and the music of the island, but was not impressed with the food, and would return for two more visits and tours in 1991 and 1992.',
  'A single was recorded during one of these visits featuring Synliga and some Cuban musicians. On the way back to Sweden the 24-track master tape was carried by Sven and he was late off the plane at the stopover at the airport in Santo Domingo and was picked up by airport security who believed that he was carrying a bomb and the fact that he was going the wrong way didn’t help matters.',
  'He managed to talk his way out of the situation and was helped back to his friends and the recordings were released as a single later the same year.',
  'On the way home to Sweden on one of the other Cuban visits the band did two gigs in Madrid, Spain, with full press coverage and TV. The group has several times tried to repeat this, but things have fallen out at the last minute. However the band still hopes to play in Spain again since they found it most gratifying.',
  'In 1991 Synliga was part of an international children’s camp headed by the “Falcon Movement” and this proved to be a turning point for the group. Playing every night for 10 days straight, and with different guests on stage every night, the band started involving humour into their stage act in a big way and from now on they would never be the same again. The verbal interplay between Sven and Ulf, which was at first totally improvised and later turned into a stage show is today part of the Synliga trademark.',
  'The use of humour in speech and lyrics made it easier for the band to get their messages across since the subject of blindness in it isn’t very funny, but now the humour and the serious in a magic mix made Synliga live or on record as strange and wondrous as the sweet and sour sauce at a China restaurant.',
  '1997 was the year when the stage show was finally realised and it was called “Blindträff”. The title is Swedish for blind date.',
  'With the help of the Swedish comedian Adde Malmberg a 1½ hour show was created and the bands first full-length CD was released. Half of this album is a studio recording and the other half is live. Two additional members, Joakim Lundberg on synthesizers and Christer Tull on guitar, joined the band to strengthen the musical side of the show and to enable the band to fully perform the complex song structures live.',
  'The group found itself in Los Angeles, USA, in 1999 and the annual congress for ACB (American Council for the Blind) and a couple of performances in association with “Friends In Art”. The group was very satisfied with the reception their English lyrics received and also the monologues from their show “Blindträff” that Sven had translated and delivered live.',
  'To make their name more suitable for ears used to the English language the band called themselves, “Out Of Sight”, but this probably only made them sound like a bunch of old hippies.',
  'English was also the language when Synliga released their next single to promote their two gigs in Tokyo in 2000. The song was written by Ulf and Sven and was called All Over the World” and was given the magic touch by the fantastic Swedish producer Johan Vävare.',
  'For the Japanese gigs the line-up was slightly changed. The original Synliga drummer Frank Skaret once again joined the band, thereby releasing Sven from The drums. The frontline on stage was now the 3 lead vocalists Marie, Sven and Ulf. Another change occurred when guitarist Kaj left the band after 17 years to devote his attention to his political career.',
  'The concerts in Tokyo were a joint venture between Synliga and the Japanese”Masaki Band” and were a huge success. The 1200 seat concert halls where sold out both nights. Synliga still dreams of going back to Japan again since they found the people and the country absolutely wonderful.',
  'Late in 2003 the band was joined by guitarist Johan Häglerud. He not only gave the band a vital musical injection but also gave the average age of the band members a well needed boost downwards.',
  'In 2006 Synliga presented a new show called, “Blind Date”.',
  'This being more than a show wanted to take the visitor on an adventure in the dark in order to give the other senses besides sight a chance to rule for a while. The first half of the show, including eating a meal, was in the dark and the second half was with the lights on. A sparkling performance with lots of dancing and surprises with choreography by the South African Graham Tainton.',
  'Graham who has worked with almost all great Swedish artists including ABBA has really taken the group under his wings and performed miracles, and has become a close personal friend to one and all in the band. The show was written by Sven and Ulf and a new member, Ulrika Norelius, joined the band on vocals, giving the band a two male, two female frontline.',
  'In 2006 the new album “Sinnenas Rum” was released. All in Swedish except for two songs in English. Most of the songs from the “Blind Date” show are included on the CD. The vocal arrangements are very special on this album and showcase some of Maries finest moments as a vocal arranger. The record is mixed with the help of David Castillo, most known for his work with “Katatonia.”',
  'Booth the albums “Blindträff” and “Sinnenas rum” are there for your musical pleasure at Spotify.',
  'At the end of 2007 the band played in Russia for the first time at the International Disability Festival held in St. Petersburg. Regular drummer Frank was unable to go and was replaced by Robert Wigand who together with Synliga faced a crowd of 9000 people that warmly welcomed the group’s music. Ulf and Ulrika sang in Russian in the song “Life” and received strong ovations for their effort.',
  'In 2008 Synliga began work on the follow up to the show “Blind Date.” The idea was to do more of the new show in the dark and new fun things to do using smell and light effects where discussed. A plan of how much time would be needed to rehearse the new material was presented and this forced keyboard player Joakim and drummer Frank to leave the project. Session drummer Pär Hedtjärn, known in Scandinavia for his work with the band “Nordman”, replaced Frank for the show and for parts of the upcoming cd.',
  'The name of the new show was, “Synliga i mörker”, meaning Synliga in the dark or visible in the dark.',
  'The two members aborting the project was only the beginning of the troubles that would haunt the production all the way.',
  'There was great difficulty in finding a good director and the one who finally did the job was quite unsuitable.',
  'Sven was unhappy with the material and felt that the show was weak and far too pretentious. He was ready to leave the project, and even the band for good, a couple of times but was persuaded to stay on.',
  'The economic crisis of the world didn’t help either and the show was only played for a couple of months in 2009 and was then put on hold.',
  'The album was given the same title as the show and was another step forward for the band. Once again musically arranged by Ulf with vocal arrangements by Marie and mixed by Ulf, Sven and David Castillo. It was undoubtedly the best Synliga album to date and sounds great!',
  '2010 continued with lots of small acoustic gigs at the tow venues “Svartkrogen” and the new one started by Marie and ulf “Svartklubben.”',
  'On July 11 Synliga played what was to be the last gig with Marie. It was a full band performance at Furuboda in the south of Sweden. The band did well despite the troublesome train journey down from Stockholm and was happy with the gig.',
  'Marie had been complaining about stomach-aches since April and this greatly worried her boyfriend Ulf and the rest of the band since she was known for not letting illness stop her. A few weeks later she was diagnosed with cancer and died on October 24. Her death left the band and all who knew her bewildered since she was such a whirlwind of energy and a driving force.',
  'Ulf who was left with their two teenage children decided to work his way through his mourning by working hard at the “Svartklubben” and this was also something he had promised Marie before she passed away.',
  'What would happen to Synliga was very uncertain but a couple of meetings later a continuation was decided upon.',
  'During 2011 the different small constellations playing at “Svartkrogen” and at “Svartklubben” had several hundred gigs. The concept seemed to grow more and more and the clubs where sold out three or four nights a week, sometimes at booth places at the same time.',
  'Bookings for the “Blind Date” show also started to come in again and Ulrika, Sven and Ulf reworked the music and the spoken parts to be able to do them as a trio. This turned out well and late 2011 they played some gigs in the northern town of Umeå with a bunch of additional gigs in the pipeline.',
  'An organization for visually impaired young people, US unga synskadade, presented for the second year a price to a person or a group that had done something vital for a greater understanding for people that are blind or visually impaired. Synliga was the proud recipient for the award 2011. The band was happy with the price money but even more with the acknowledgement for their hard work and persistence.',
  'with An album featuring the music of Marie was released in the summer of 2011. It was a compilation of recordings from her entire career and included a few tracks by Synliga. The album was called “Marie Häglerud – Glöden som aldrig falnar” and was to be followed by an album with previously unreleased material by the late singer and musician in 2012.',
  'It was also decided as a last decicion of 2011 to make a new album under 2012. If it was to be a new studio recording or maybe a compilation of live material gathered through the years was not determined.',
  '2012',
  'This year continued pretty much as the previous year with lots of small gigs in the dark.',
  'The work on the new album was postponed but Ulf gathered a fair amount of new songs to be worked on as soon as the band could find the time.',
  'Synliga had one major gig during the year and it took place in the center of Stockholm in a park called “Kungsträdgården.”',
  'It was a great beautiful sunny day and the band was in good form.',
  'This gig was also a release party for the latest album “Synliga I mörker.” Follow the link below to watch the song Kärleken är blind idag” filmed on this occasion.',
  'In September the bass player Ulf finally opened his own restaurant, “Svartklubben”, and there is now a place to go when you want to eat a meal and hear great music in the dark right in the city of Stockholm, and the new address is Södermannagatan 27.',
  'Synliga guitar player Johan Häglerud released the first single from his forthcoming album, and you can listen to it by following the link below. It’s well worth a spin and is a catchy tune with lyrics full of summer and the hope of young love.',
  'Towards the end of the year the band finally kicked off on recording the new songs and a drum session with Frank resulted in three tracks to keep working on.',
  'Different constellations of”Synliga” did 130 gigs in the dark in 2013.',
  'Christer laid down some great basic tracks and Ulf & Sven worked on them each Wednesday in the “Ljudolf-studio” in Stockholm. Other members came in now and then to add their parts to the gigantic musical puzzle that will one day be the new album by the band.',
  'On June 15 the two band members Ulrika and Joakim got married at Skansen in the heart of Stockholm and are now Mr. and Mrs. Centervik.',
  'The music for a musical about guide dogs was written by Ulf and it aired for the first time on Swedish radio in the beginning of December. The title is “Hundringar” and is a word game fusing the words for dogs and wondering together.',
  'Ulf wrote most of the songs and lyrics on a Christmas album called “Jul Jul strålande Ljudolf” and it was released at the end of December. Several of the members of “Synliga” appear on the album. If you want to give it a listen follow the link below.',
  'Jul jul strålande Ljudolf on Spotify',
  'December was also the month when Sven published his first book. The title is “Se upp jag hör dig!/Look out I can hear you!” and it is a journey from full sight to total blindness. The book is filled with humor and can also bring a tear to sensitive eyes. Lots of crazy situations and memories from life as a musician offer a unique insight into the world of a blind person’s life and way of thinking. The book has not yet been translated to English.',
]

const recentBiography = [
  `On May 17, 2014, Synliga played at a jubilee for the Swedish Association for the Blind that was broadcasted on the radio.`,
  `May 29 Ulf, Johan & Sven went to Malmö to play at an international goalball tournament. The performance was in English and received an enormous response and was all in all a joyous occasion.`,
  `Late in the summer of the year the band got an invitation to play at a music festival in Thailand. The theme for the festival was “rhythm & blind” and was to be held in Chiangmai. Sven wrote English lyrics for the songs that yet didn’t have such and Ulf and Ulrika learned a chorus in Thai. They were helped with the pronunciation by a Thai musician called Mr. Jack on location in Thailand.`,
  `On February 13 and 14 2015 Synliga performed and the second gig was the absolute best. The band was very impressed by how professional and well run the festival was and how sweet and warm the organizers were towards the band members.`,
  `Besides the wonderful Thai people, we also met a Brazilian singer and dancer by the name of Sara Bentes. Sven and Sara had some contact by mail before the trip and when Synliga and Sara got together a bond was formed right there and then. Sara tried to teach the band to dance the samba with minor success but plans to make music together were formed.`,
  `To coincide with the trip a song written by Ulf, “Vilken tur”, was released and can be heard on Spotify and other streaming services. The English version with lyrics by Sven, “Fortune Smiles”, in a live version from the festival can be seen and heard on YouTube.`,
  `In the beginning of April Ulf, Johan & Sven once again travelled to Malmö for another gig at an international tournament of goalball. With the English lyrics still fresh in mind the performance was more than well received.`,
  `Hundreds of gigs at the two restaurants for dining in the dark Svartkrogen and Svartklubben were the main things in the following years. To say that our Swedish version with the music of Synliga mixed with fine dining was a thunderous success is an understatement.`,
  `The Brazilian whirlwind Sara Bentes came to Sweden several times and played with the band at the events in the dark and other gigs. At every visit she talked about how great it would be if Synliga could come to Brazil for gigs with her. The band members felt eager and the plans grew stronger.`,
  `Having been a member since 1997 Joakim was asked to leave due to musical differences but continued to work with Johan, Ulrika & Sven at Svartkrogen at Almåsa Havshotell.`,
  `Once again members of Synliga boarded a train going south to Malmö for yet another international tournament in goalball. This time it was Johan, Sven & Frank that entertained the players and the reception was as always loud and enthusiastic.`,
  `The pandemic made life difficult for the band and the rest of the world but in 2023 things started to normalize.`,
  `An invitation to participate in a blind version of the Eurovision Song Contest by the German Association for the Blind came to the band. Johan remembered that Ulf had a good song lying around that could be suitable, so the band said yes and got to work. Sven wrote some new lyrics, and Johan did some arranging and with some additional recording and heartful singing the song was completed. On Spotify you can find, “We’re Gonna Have a Party Tonight.” The song didn’t win but since it was Ukraine that won it didn’t feel too bad. Synliga hoped that Ukraine would also win on the battlefield against the Russian aggressors.`,
  `2023 was also the year that Synliga finally made it to Brazil. Before the trip we wrote two songs, and they included both Synliga and Sara Bentes. Synliga did their recording in Sweden and then the files got sent to Brazil and Sara did her vocals and sent the files back. The first track was a lyric by Sven that he sent to Ulf who right away put a magic melody to it and “A Long Time Coming” was born. Track 2 was an old song of Ulf’s that instead of the not so serious lyrics in Swedish was fitted with Portuguese lyrics. The 2 songs were arranged and produced by Johan and Sven and can be fully enjoyed at Spotify and other streaming services.`,
  `In July the band, Ulf Nordquist on vocals and acoustic guitar, Johan Häglerud on bass and vocals, Ulrika Norelius on vocals and keyboard, Frank Skaret on drums, Sven Westin on vocals and percussion, and to complete the lineup the guitar player Anders Snucke Wideland who replaced Christer Tull who didn’t want to go. Two assistants or roadcrew in form of Ann-Louise Forneman and Annika Otterstål completed the travelling band.`,
  `Gigs in the 3 cities of Sao Paulo, Volta Redonda and Rio De Janeiro plus sightseeing and visits to numerous musical events made the 2 weeks in Brazil a memory for life. The audiences in Brazil were fantastic and left the band wanting for more.`,
  `2024 and a year later Synliga had come of age and was now 40 going on 41. A jubilee was arranged and played at Årsta Folketshus. Sara Bentes was flown in from Brazil, and the band played 2 sets consisting of songs from the bands long career and a few of Saras hits. Through modern magic Synliga played a song with Marie Häglerud on vocals who we lost to cancer so many years ago. It was a very heartful moment, and the number was placed at the end of set 1 so we all could recharge and pull ourselves together for the remainder of the gig. Knowing that it’s bad to tell a lie the band still promised to return when it was time to celebrate another 40 years.`,
  `Lots of gigs in the dark followed with occasional trips for concerts in other parts of Sweden than Stockholm. Both Värmland and Dalarna was visited by the trio Johan, Ulrika & Sven. It’s nice to be seen sometimes!`,
  `In 2025 and 2026 plans for a re-visit to Brazil started to take form and it was drummer Frank that was the most eager this time. Everybody was soon aboard and it was all systems go. Then came the phone call from Ulf saying that he was unable to come along due to business and family affairs. We needed someone to take his place, and we had the perfect fit right under our noses in the pianoplayer, flutist and singer Sara Backström Lindeberg who already played with Johan, Ulrika & Sven at Svartkrogen where she since a while back had replaced Joakim. After the first rehearsal we knew that this had been a stroke of genius since the band sounded great right of the bat.`,
  `To the shock of all Joakim Centervik suddenly died from heart failure. Much too young Joakim left this life and if there is heaven, he’s there and is most probably discussing how to get the best sound out of a Hammond organ with Jon Lord and Keith Emerson.`,
  `On June 3, 2026, the band with Sara replacing Ulf but otherwise the same gang as the last time lifted from Swedish soil for the long trip to Brazil. To no surprise the second visit was just as fantastic as the first one and Synligas love for Brazil grew even stronger.`,
  `There was no new music released but Sven had written 2 new lyrics. One was a strange love song about a Swedish guy and a Brazilian girl who tries to impress the other to strike up interest. He claims that he eats meatballs for breakfast and rides his own moose and that he writes better songs than ABBA and Max Martin. She claims that she watches soccer all day long and then she goes dancing all night because it’s all play and no work. Being from the town of Volta Redonda, she has an Anaconda. There should be love between them but as it says in the song, “love can’t see a thing today.”`,
  `The second lyric is a translation of the lyric Sven wrote to the song, “Känsliga händer”, that in English became, “Sensitive Fingers.” According to Sven in this song blind men have a magic touch and are able to give a sublime massage and endless pleasure with their sensitive fingers. It could be the truth, or it could be a falsehood but in Swedish or English these lyrics are very entertaining. All was well until the last gig in Rio De Janeiro. Just before the start of the gig Sven and the others were told by Sara Bentes that there were 4 nuns in the audience. Sven is not a religious man but didn’t want to make life difficult for the nuns and proposed to Sara that the song should be omitted from the playlist. She said a definitive no to this and claimed that the religious ladies would be fine. Sven sang his song and did the usual sex noises and to his surprise the nuns started giggling and seemed to enjoy themselves enormously. Fun is fun and never underestimate the humor of a nun!`,
]

function AboutEnglish() {
  return (
    <section className="max-w-4xl">
      <p className="mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-emerald-300">
        Synliga in English
      </p>
      <h1 className="text-4xl font-bold text-white sm:text-5xl">Biography</h1>
      <div className="mt-8 space-y-5 text-base leading-8 text-zinc-300 sm:text-lg">
        {[...biography, ...recentBiography].map((paragraph, index) => (
          <p key={`${index}-${paragraph}`}>{paragraph}</p>
        ))}
      </div>
    </section>
  )
}

export default AboutEnglish
